spring:
  datasource:
    activiti:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/activity?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件 ,默认校验resources下的processes文件夹里的流程文件
    #1.flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    #2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    #3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    #4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.minn.springbootdroolsactivity.entity
